### ISSUE TITLE
Exceptions on startup

### ISSUE THREAD

**Issue by Smitty010** [guopenghui/obsidian-quiet-outline#190]
I'm seeing a lot of exceptions:

app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at eval (plugin:obsidian-quiet-outline:1006:25646)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-quiet-outline:1006:25616)
    at e.tryTrigger (app.js:1:722865)
    at e.trigger (app.js:1:722798)
    at t.trigger (app.js:1:2306669)
    at t.<anonymous> (app.js:1:2247453)
    at l (app.js:1:518110)
    at c (app.js:1:518226)

**Comment by Drakemoor** [comment]
I have the same issue.

**Comment by albertoloscerritos** [comment]
same here

**Comment by Drakemoor** [comment]
this issue persists on obsidian 1.7.4 installer as well. 
```
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at eval (plugin:obsidian-quiet-outline:1006:25646)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-quiet-outline:1006:25616)
    at e.tryTrigger (app.js:1:722881)
    at e.trigger (app.js:1:722814)
    at t.trigger (app.js:1:2371835)
    at t.<anonymous> (app.js:1:2311031)
    at l (app.js:1:518110)
    at c (app.js:1:518226)
eval @ plugin:obsidian-quiet-outline:1006
eval @ plugin:obsidian-quiet-outline:1006
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
l @ app.js:1
c @ app.js:1
setTimeout (async)
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
l @ app.js:1
c @ app.js:1
setTimeout (async)
u @ app.js:1
t.updateLayout @ app.js:1
r @ app.js:1
```

Let me know if I can provide more info for the issue to be resolved. 

Thank you for your good work.

**Comment by guopenghui** [comment]
try version `0.3.37`

**Comment by Drakemoor** [comment]
This fixed if. 
Thank you for the great plugin.
