### ISSUE TITLE
两个bug报告（有时一片空白和搜索后出错）

### ISSUE THREAD

**Issue by PenguinWang123** [guopenghui/obsidian-quiet-outline#194]
bug报告：1、有时会一片空白，没有任何大纲显示；2、在quiet outline搜索并仅显示搜索的大纲后，在删除搜索文字后，quiet outline仍然仅呈现搜索的大纲，而不是完整显示所有大纲
<img width="481" alt="截屏2024-11-06 14 11 20" src="https://github.com/user-attachments/assets/55e74eb9-44ff-4fe3-b2f3-1d873e4cf57c">

**Comment by PenguinWang123** [comment]
这个bug一直存在，希望作者修复

**Comment by yanqing-song** [comment]
我也有同样的问题，但不是每次都出现，看同一个 md文件，有时是好的，有时搜索大纲之后会空白。出现空白后，重启 obsidian 就没问题了， 但是过一会不知怎的又出现了...

**Comment by PenguinWang123** [comment]
> 我也有同样的问题，但不是每次都出现，看同一个 md文件，有时是好的，有时搜索大纲之后会空白。出现空白后，重启 obsidian 就没问题了， 但是过一会不知怎的又出现了...

没错，一样的

**Comment by PenguinWang123** [comment]
> 能制作一个一定会复现问题的md文件吗，我这边复现不出来

制作不了，我们出现问题的都是我们自己信息的文档，没法po出来……哎这问题太常见了，不知道怎么办好

**Comment by PenguinWang123** [comment]
继续报告，在quiet line中搜索文本后，quiet line的大纲经常就停留在了搜索结果的大纲，而不是完整显示，我经常需要先关闭quiet line插件然后再重启调出来，这个bug天天出现

**Comment by PenguinWang123** [comment]
> 能制作一个一定会复现问题的md现文件吗，我香料复不出来




你好，这个文件在搜索时出问题了，但是这个文件上传时一直显示“failed to upload”为什么呀

**Comment by PenguinWang123** [comment]
> 能制作一个一定会复现问题的md现文件吗，我香料复不出来

通过网盘分享的文件：test quiet line.md
链接: https://pan.baidu.com/s/1uKHR0OAG4aNnzkO8kzx1jQ?pwd=5pkw 提取码: 5pkw 
--来自百度网盘超级会员v8的分享
你好，这个文件在搜索后大纲停留在搜索结果的大纲了（由于直接上传md文件一直失败所以用网盘传，永久有效）

**Comment by guopenghui** [comment]
https://github.com/user-attachments/assets/cfeffcf0-685f-4998-b2c8-f643202db7d5

还是没能复现出来。你可以打开控制台，然后再在大纲里搜索一下，看控制台有没有什么报错信息。

**Comment by PenguinWang123** [comment]
> PixPin_2025-03-04_17-33-42.mp4 
> 还是没能复现出来。你可以打开控制台，然后再在大纲里搜索一下，看控制台有没有什么报错信息。

VM1087 plugin:obsidian-quiet-outline:1003 Uncaught TypeError: h.current_note.getMode is not a function
    at HTMLDocument.k (plugin:obsidian-quiet-outline:1003:6622)
    at l (app.js:1:518110)
    at c (app.js:1:518226)
6plugin:obsidian-quiet-outline:1003 Uncaught TypeError: h.current_note.getMode is not a function
    at HTMLDocument.k (plugin:obsidian-quiet-outline:1003:6622)
    at l (app.js:1:518110)
    at c (app.js:1:518226)
VM306 plugin:obsidian-quiet-outline:1003 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLDocument.k (plugin:obsidian-quiet-outline:1003:6459)
    at l (app.js:1:518110)
    at c (app.js:1:518226)
VM1087 plugin:obsidian-quiet-outline:1003 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLDocument.k (plugin:obsidian-quiet-outline:1003:6459)
    at l (app.js:1:518110)
    at c (app.js:1:518226)
plugin:obsidian-quiet-outline:1003 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at HTMLDocument.k (plugin:obsidian-quiet-outline:1003:6459)
    at l (app.js:1:518110)
    at c (app.js:1:518226)

<img width="720" alt="Image" src="https://github.com/user-attachments/assets/7599f4c3-cd25-44db-acda-c543b1156994" />

**Comment by guopenghui** [comment]
能不能提供一下下面的信息，出问题时的：
+ obsidian版本号
+ quiet outline 版本号
+ 使用的主题

另外也可以尝试一下关闭其他插件，然后再试一下看能不能出同样的问题

**Comment by PenguinWang123** [comment]
> 能不能提供一下下面的信息，出问题时的：
> 
> * obsidian版本号
> * quiet outline 版本号
> * 使用的主题
> 
> 另外也可以尝试一下关闭其他插件，然后再试一下看能不能出同样的问题。可以的话录屏一下，看看是什么使用操作下出这样的问题

> * obsidian版本号：Version 1.7.4 (Installer 1.5.3)
> * quiet outline 版本号：0.3.40
> * 使用的主题：Blue Topaz

**Comment by PenguinWang123** [comment]
> Blue Topaz 是最新版本吗 :2024121301

不是，我的版本是：2023111501 但是我很担心主题更新后会不会影响我的一些现有使用，好像blue topaz之前有一些问题，但我记不清了

**Comment by guopenghui** [comment]
版本都比较旧，不太好找问题，看后面有没有机会遇到吧。

目前看起来可能和滚动(scroll)相关，scroll事件的对象到了document上，但 document 对象上面没有 classList，所以在调用 document.classList.contains 的时候发生错误。 但是为什么会有 scroll 事件的target会变成document，目前还不太清楚，一般滚动仅仅是在页面内某个元素上发生的。

你可以试下用其他主题的时候能不能重现这个错误。

**Comment by guopenghui** [comment]
鉴于 obsidian 和 quiet outline 和 bluetopaz 在这期间经过了多次更新，很难再确定旧版本上的问题。
因此关闭这个 issue。
如果三者都更新到最新版本仍有相同问题，可以新打开一个 issue
